name: zedpass
description: "ZedPass - Secure SSTP VPN Client"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sstp_flutter: ^1.3.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "ZedFlow.png"
  adaptive_icon_background: "#1C1C1E"
  adaptive_icon_foreground: "ZedFlow.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true
  assets:
    - assets/images/
